title: CLImate
tagline: PHP's best friend for the terminal.
description: Colors, formatting, debugging and more when running PHP from the command line.
google_analytics_tracking_id: UA-46050814-8
menu:
    Getting Started:
        Introduction: '/'
        Installation: '/installation/'
        Basic Usage: '/basic-usage/'
    Styling:
        Colors: '/styling/colors/'
        Formatting: '/styling/formatting/'
        Combinations: '/styling/combinations/'
        Commands: '/styling/commands/'
        Customizing: '/styling/customizing/'
    Terminal Objects:
        Overview: '/terminal-objects/overview/'
        Input: '/terminal-objects/input/'
        Table: '/terminal-objects/table/'
        Border: '/terminal-objects/border/'
        Progress Bar: '/terminal-objects/progress-bar/'
        JSON: '/terminal-objects/json/'
        Dump: '/terminal-objects/dump/'
        Flank: '/terminal-objects/flank/'
        Break: '/terminal-objects/br/'
        Draw: '/terminal-objects/draw/'
        Clear: '/terminal-objects/clear/'
